from os import environ
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DEFAULT_DATABASE_PATH = DATA_DIR / "automations.db"
DEFAULT_UPLOAD_TEMP_DIR = DATA_DIR / "uploads"

DATABASE_PATH = Path(
    environ.get("DATABASE_PATH", str(DEFAULT_DATABASE_PATH))
).expanduser()
UPLOAD_TEMP_DIR = Path(
    environ.get("UPLOAD_TEMP_DIR", str(DEFAULT_UPLOAD_TEMP_DIR))
).expanduser()
AUTH_USER = environ.get("USER_APP")
AUTH_PASSWORD = environ.get("PASSWORD")
SECRET_KEY = environ.get("SECRET_KEY")
SESSION_COOKIE_SECURE = environ.get("SESSION_COOKIE_SECURE", "False")
SESSION_LIFETIME_HOURS = int(environ.get("SESSION_LIFETIME_HOURS", "1-4b"))
TRUST_PROXY = environ.get("TRUST_PROXY", "False")
LOGIN_RATE_LIMIT_ATTEMPTS = int(environ.get("LOGIN_RATE_LIMIT_ATTEMPTS", "5"))
LOGIN_RATE_LIMIT_WINDOW_SECONDS = int(
    environ.get("LOGIN_RATE_LIMIT_WINDOW_SECONDS", "900")
)
LOGIN_RATE_LIMIT_BLOCK_SECONDS = int(
    environ.get("LOGIN_RATE_LIMIT_BLOCK_SECONDS", "900")
)
MAX_UPLOAD_SIZE_MB = int(environ.get("MAX_UPLOAD_SIZE_MB", "20"))
MAX_UPLOAD_SIZE_BYTES = MAX_UPLOAD_SIZE_MB * 1024 * 1024
MAX_XLSX_UNCOMPRESSED_SIZE_MB = int(environ.get("MAX_XLSX_UNCOMPRESSED_SIZE_MB", "100"))
MAX_XLSX_UNCOMPRESSED_SIZE_BYTES = MAX_XLSX_UNCOMPRESSED_SIZE_MB * 1024 * 1024
MAX_SPREADSHEET_ROWS = int(environ.get("MAX_SPREADSHEET_ROWS", "5000"))
MAX_SPREADSHEET_COLUMNS = int(environ.get("MAX_SPREADSHEET_COLUMNS", "100"))
MAX_SPREADSHEET_CELLS = int(environ.get("MAX_SPREADSHEET_CELLS", "100000"))

CPFL_API_URL = environ.get("CPFL_API_URL", "")
CPFL_CITY_IDS = {
    "Cosmopolis": 59,
    "Paulinia": 116,
}

RANGE_DAYS_CONSULT = int(environ.get("RANGE_DAYS_CONSULT", "3"))
SEND_NUMBERS = environ.get("SEND_NUMBERS")


EVO_API_KEY = environ.get("EVO_API_KEY")
EVO_URL = environ.get("EVO_URL")
INSTANCE = environ.get("INSTANCE")

GMAIL_USER_ID = environ.get("GMAIL_USER_ID", "me")
GMAIL_SENDER = environ.get("GMAIL_SENDER")
GMAIL_LABEL = environ.get("GMAIL_LABEL")
GMAIL_QUERY = environ.get("GMAIL_QUERY")
GMAIL_MAX_RESULTS = int(environ.get("GMAIL_MAX_RESULTS", "10"))

GOOGLE_CREDENTIALS_FILE = environ.get("GOOGLE_CREDENTIALS_FILE")
GOOGLE_TOKEN_FILE = environ.get("GOOGLE_TOKEN_FILE")
GOOGLE_DRIVE_FOLDER_ID = environ.get("GOOGLE_DRIVE_FOLDER_ID")
GOOGLE_DRIVE_SHARE_TYPE = environ.get("GOOGLE_DRIVE_SHARE_TYPE")
GOOGLE_DRIVE_SHARE_ROLE = environ.get("GOOGLE_DRIVE_SHARE_ROLE", "reader")
GOOGLE_DRIVE_SHARE_DOMAIN = environ.get("GOOGLE_DRIVE_SHARE_DOMAIN")

DRIVE_UPDATE_GOOGLE_CREDENTIALS_FILE = environ.get(
    "DRIVE_UPDATE_GOOGLE_CREDENTIALS_FILE"
)
DRIVE_UPDATE_SHEET_NAME = environ.get("DRIVE_UPDATE_SHEET_NAME")
DRIVE_UPDATE_WORKSHEET_NAME = environ.get("DRIVE_UPDATE_WORKSHEET_NAME")
