REQUIRED_COLUMNS = [
    "SERVICO",
    "AGENDAMENTO",
    "CTDTDATAAGENDA",
    "CTNOMESLOT",
    "LOCALIDADE",
    "PROTOCOLO",
    "CTDTSOLICITACAO",
    "CLIENTE",
    "ENDERECO",
    "BAIRRO",
]
